### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by dianin5** [JJutopsy/RDE-Tools#5]
# [오늘 스듀 task]

### 평범한 날

- [x] 용암장어 낚기(광산 100층)
- [x] 전갈잉어 낚기(사막)
- [x] 숲고기 낚기(마녀의 숲)
- [x] 돌연변이 잉어(하수구)
- [ ] 공허의연어 낚기(마녀의 늪)

### 비오는날

- [x] 메기 낚기(강(마을,숲))
- [x] 월아이 낚기(강(마을,숲))

## 박물관
현지 제외
- [x] 박물관 가서 보상 받아오기(결정생성기, 피뢰침 설치)

## 채광
- [x] 9레벨 찍고 결정생성기 제작
- [x] 사막광산 25층 찍기

**Comment by dianin5** [comment]
마녀의 숲 못뚫음, 피뢰침 없음, 결정생성기 배터리팩 들어서 뇌우가 와야 가능함 이 외에 완료
